### ISSUE TITLE
Placing doesnt work from all sides after random time

### ISSUE THREAD

**Issue by tchncs** [BlockMen/torches#10]
Hi, we are on Commit #5009d31 with our Server.

After a random time the placing of new torches doesnt work correctly.
Its only possible from one side - so the server needs a restart.
We sadly dont know how to reproduce it, its only digging and placing, like anyone... .

![screenshot_20150824_160155](https://cloud.githubusercontent.com/assets/10698140/9442143/7df682bc-4a7a-11e5-909f-77915ab82b17.png)

```
...
2015-08-24 16:01:10: ACTION[ServerThread]: Milan places node torches:wall at (1244,15,749)
2015-08-24 16:01:10: ACTION[ServerThread]: attached node torches:wall can not be placed at (1244,15,749)
...
```

**Comment by BlockMen** [comment]
@tchncs What other mods are you using?

And are you sure this happens only with torches and not with other nodes aswell, e.g. slabs/stairs? Because I have no idea how this bug should be causes by time...

**Comment by tchncs** [comment]
Hi, thanks for your answer.
Maybe the problem has startet by installing the technic mod, but im not sure about it.

Here is our Modlist:
```
3d_armor     
darkage            
mobf_trader  
mr_goat            
scaffolding  
travelnet
arrow_signs  
farming_plus       
mobs         
mushrooms          
stairsplus   
unifieddyes
biome_lib    
homedecor_modpack  
mobs_sky    
pipeworks          
stats
bitchange    
kickall            
moreblocks  
 plantlife_modpack  
steel
boost_cart   
medieval_craft     
moreglass    
quartz             
technic
cannons      
mesecons           
moreores     
random_buildings   
the_list
craft_guide  
mini_sun           
moretrees    
replacer           
torches
```

**Comment by BlockMen** [comment]
Hmm...too many mods and (for me) too many unknown ones to say anything about those.

But from what it looks like on the second image you posted i guess some other mod is overriding the torch again, so the needed place code (of this mod) cant work anymore.

So best to fix this would be if you search the mod that changes the `default:torch` item and merge the change with this mod or vice versa.

**Comment by BlockMen** [comment]
@tchncs is this issue still present and did you find out something or can this get closed?

**Comment by tchncs** [comment]
Its still present - sorry, i tryed some things to reproduce it and give you some debug log, but i failed.
Im still pretty sure it have something todo with the technic mod, but there is nothing about default:torch in the code. thats sad.

i manage two servers. one of them is nearly 1:1 the same as the other one.
the only mod it doesnt have is technic. the 3d torches working fine there.

**Comment by BlockMen** [comment]
Hmm...that is really strange. I couldnt find something on special node handling in technic either, that could explain this issue.
Only idea that i have now is to add technic to depends.txt of torches, then you ensure it gets loaded after technic, but i doubt it will help.

**Comment by tchncs** [comment]
Interesting idea - will try that out and tell you if the issue happen again.. .
This will take a hour upto three days.^^

**Comment by tchncs** [comment]
````
2015-10-09 22:28:39: ACTION[Server]: Passant places node torches:wall at (-14,-2301,3311)
2015-10-09 22:28:39: ACTION[Server]: attached node torches:wall can not be placed at (-14,-2301,3311)
````
:-(

**Comment by BlockMen** [comment]
Ok, thats interesting. Could you try if it works again with pipeworks disabled?

I have still no clue, but it could be somehow related with a function in pipeworks because of the "simulated players" in there.

**Comment by BlockMen** [comment]
Sry, forgot that technic depends pipework ...

Ok, here might be the solution: https://github.com/BlockMen/torches/commit/b70aa0f2ce909e5c304dfea1fee2162504ba1e78

If technic or any related mod sets a global dir it would cause this issue. You had somewhere the warming of using an undeclared global named "dir"? If not im pretty sure this is the cause.

**Comment by tchncs** [comment]
Ouh, sorry about my delay.
I will try your (hopefully) fix now.
The only "dir" Warning i can find is from the technic mining_drill:

````
...inside a function at ...etest/bin/../mods/technic/technic/tools/mining_drill.lua:157.
````

**Comment by tchncs** [comment]
Looks like its fixed now.
Really cool, thank you! :-)

**Comment by BlockMen** [comment]
Good, finally :)
