### ISSUE TITLE
Wrong torch positionning

### ISSUE THREAD

**Issue by kilbith** [BlockMen/torches#4]
When you place a torch on a ceiling, the torches are not reversed (and straight)...

![screenshot_2475948299](https://cloud.githubusercontent.com/assets/7883281/6217003/9e514934-b60f-11e4-8214-79ab4fce965d.png)

**Comment by kilbith** [comment]
Sorry, didn't noticed that's a feature : « ceiling placed torches are removed. »

But however, this is a mistake. It's common that players use it on ceiling.

**Comment by BlockMen** [comment]
> But however, this is a mistake. It's common that players use it on ceiling.

I hate ceiling torches :P


> « ceiling placed torches are removed. » 

thats only for "old"/default torch conversion, so your bug report was correct. reopening

**Comment by kilbith** [comment]
You should add the ceiling torches if you expect add them in minetest_game (it'd be appreciated).

**Comment by BlockMen** [comment]
This mod won't ever go in minetest_game for several reasons. The most important is, that the way flames are handled are too laggy, we need an engine change to do that in a sane way clientside.
Then there are a few (a lot?) ppl that would complain because its toooo MC-like, and so on...

So the ceiing torches will be never in this mod ;)

**Comment by kilbith** [comment]
> Then there are a few (a lot?) ppl that would complain because its toooo MC-like, and so on...

A few, and we know who are those primitive haters... In other hand, the current default torch looks like a lit shit and the flames are negligible until a better engine's handling.

**Comment by HybridDog** [comment]
These primitive haters didn't seem to have much success.
Minetest even has a similar water transparency bug.

**Comment by BlockMen** [comment]
Until particles are handled better i would like to improve torches by this, but read the "discussion" yourself: https://github.com/minetest/minetest/pull/1328

**Comment by BlockMen** [comment]
Fixed by e77b69900cc6d86c34fa6e3406267b7efe94f5bf
